// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMf3_KOUUiNhL-SxSV1CF_rWG_aEXEJfI',
    appId: '1:483631601866:web:cfd89dc1c7245744073c33',
    messagingSenderId: '483631601866',
    projectId: 'skillsync-free',
    authDomain: 'skillsync-free.firebaseapp.com',
    databaseURL: 'https://skillsync-free-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skillsync-free.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkmLL5KbVGhunDfW_FmYDYIlpe_qpJs1c',
    appId: '1:483631601866:android:602f91d36f72a5b8073c33',
    messagingSenderId: '483631601866',
    projectId: 'skillsync-free',
    databaseURL: 'https://skillsync-free-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skillsync-free.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwkrem71m7j1nYd_wGyZNnjX4Jatm29xg',
    appId: '1:483631601866:ios:207ea28cc4cdf55b073c33',
    messagingSenderId: '483631601866',
    projectId: 'skillsync-free',
    databaseURL: 'https://skillsync-free-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skillsync-free.firebasestorage.app',
    iosBundleId: 'com.techwing.qrAttendanceScanner',
  );
}